

[server]
[server.init]

[server.set_router]

[server.add_resource]
[server.load_resource]
[server.set_listener]
[server.start]
[server.stop]
*/
// 设置路由
s.SetRouter(cpis.NewRouter())
// 加载资源
s.AddResource(cpis.ConfigAPI())
s.AddResource(eventapi.GetEventAPI())
s.LoadResource(ctx)
// 设置监听器

	s.SetListener(ctx, []structs.Listener{
		listeners.PeripheralListenerInstance(), // 外设监听
		listeners.HSListenerInstance(),         // HS监听
	})

// 启动
s.Start(ctx)
// 等待退出
s.Stop(ctx)